### ISSUE TITLE
Behavioral Modeling - Sequence Diagram

### ISSUE THREAD

**Issue by mahyaj98** [mahyaj98/SW_InfluencerMarketing#10]
--------- Mahya --------- 
- [x] Influencer Search

- [x] Influencer Suggestion

- [x] Pricing for an Influencer

--------- Mehrdad--------- 

- [x] Rating System

- [x] Feedback Analysis

- [x] Reporting

--------- Fateme--------- 

- [x] Registeration

- [x] Login

- [x] Edit Profile

--------- Negar--------- 

- [x] Request Submission

- [x] Validate a Request

- [x] Modify/Delete a Request

**Comment by NegarSa** [comment]
Request Submission and Modify/Delete a Request are uploaded, 

- [x] Modify/Delete a Request might be updated.

**Comment by mahyaj98** [comment]
Influencer Search, Influencer Suggestion, and Influencer Pricing sequence diagrams have been uploaded, by different scenarios.

**Comment by NegarSa** [comment]
All diagrams are uploaded.
