### ISSUE TITLE
Communication Diagrams

### ISSUE THREAD

**Issue by mahyaj98** [mahyaj98/SW_InfluencerMarketing#11]
--------- Mahya --------- 
- [x] Influencer Search

- [x] Influencer Suggestion

- [x] Pricing for an Influencer

- [x] Recommending System core

--------- Mehrdad--------- 

- [x] Rating System

- [x] Feedback Analysis

- [x] Reporting

--------- Fateme--------- 

- [x] Registeration

- [x] Login

- [x] Edit Profile

--------- Negar--------- 

- [x] Request Submission

- [x] Validate a Request

- [x] Modify/Delete a Request

**Comment by mahyaj98** [comment]
Influencer Search, Influencer Suggestion, Influencer Pricing, and Recommeding System Core communication diagrams have been uploaded.

**Comment by fatemeh-ra** [comment]
communication diagrams uploaded completely
