### ISSUE TITLE
Activity Diagrams

### ISSUE THREAD

**Issue by mahyaj98** [mahyaj98/SW_InfluencerMarketing#6]
Upload activity diagrams for the system.

**Comment by mehrdadmms** [comment]
Activity diagrams 

- [x] Registration 

- [x] Login

- [x] Request advertisement

- [x] Analyze

- [x] Transaction

- [x] reporting 

- [x] Search influencer

- [x] Edit request

- [x] Edit profile

**Comment by mahyaj98** [comment]
All activity diagrams have been drawn and uploaded.
